### ISSUE TITLE
项目启动npm run serve报错

### ISSUE THREAD

**Issue by eeezae** [anncwb/vue-vben-admin#1032]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

最新code安装依赖后，npm run serve 报错

```
 npm run serve


> vben-admin@2.7.0 serve
> npm run dev


> vben-admin@2.7.0 dev
> vite

Pre-bundling dependencies:
  vue
  pinia
  vue-router
  ant-design-vue
  vue-i18n
  (...and 76 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/@vueuse/shared/index.esm.js:1:9: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "computed"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵          ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:19: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "unref"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                    ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:26: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "watch"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                           ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:33: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "ref"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                  ~~~

 > node_modules/@vueuse/shared/index.esm.js:1:38: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "customRef"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                       ~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:57: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "isRef"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                          ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:64: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "reactive"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                 ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:74: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "toRef"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                           ~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:89: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "getCurrentInstance"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                                          ~~~~~~~~~~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:109: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "onMounted"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                                                              ~~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:120: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "nextTick"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                                                                         ~~~~~~~~

 > node_modules/@vueuse/shared/index.esm.js:1:130: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "onUnmounted"
    1 │ import { computed, unref, watch, ref, customRef, isVue3, isRef, reactive, toRef, isVue2, getCurrentInstance, onMounted, nextTick, onUnmounted } from 'vue-demi';
      ╵                                                                                                                                   ~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 12 errors:
node_modules/@vueuse/shared/index.esm.js:1:9: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "computed"
node_modules/@vueuse/shared/index.esm.js:1:19: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "unref"
node_modules/@vueuse/shared/index.esm.js:1:26: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "watch"
node_modules/@vueuse/shared/index.esm.js:1:33: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "ref"
node_modules/@vueuse/shared/index.esm.js:1:38: error: No matching export in "node_modules/@vueuse/shared/node_modules/vue-demi/lib/index.mjs" for import "customRef"
...
    at failureErrorWithLog (/Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:1449:15)
    at /Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:1236:14
    at /Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/mc/Project/Escript/vue-vben-admin/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本: 15或16都有
- 包管理器 (npm/yarn/pnpm) 及其版本: npm 7.18

**Comment by JacksMaster** [comment]
把node_modules删掉重新用yarn install拉取依赖试试。或者检查vue-demi这个依赖有没有拉下来

**Comment by eeezae** [comment]
vue-demi拉下来了，但是奇怪的是npm安装的时候vue-demi下面的vue依赖是2.6.14的，用yarn安装后是正常了
