### ISSUE TITLE
运行的时候有一个报错，不晓得是哪里的问题

### ISSUE THREAD

**Issue by kinterq** [anncwb/vue-vben-admin#115]
好像是/build/script/preserve.ts脚本的报错[]
If you have no idea what this means or what Pirates is, let me explain: Pirates is a module that makes is easy to implement require hooks. One of the require hooks you're using uses it. One of these require hooks didn't return anything from it's handler, so we don't know what to do. You might want to debug this.
    at Object._compile (G:\software\project\tb-project\django-vue\myweb\20201103\20201103\ant-admin-exps\node_modules\pirates\lib\index.js:96:21)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .ts] (G:\software\project\tb-project\django-vue\myweb\20201103\20201103\ant-admin-exps\node_modules\pirates\lib\index.js:104:7)
child_process.js:655
    throw err;
    ^

Error: Command failed: node -r G:\software\project\tb-project\django-vue\myweb\20201103\20201103\ant-admin-exps\node_modules\esm\esm.js -r G:\software\project\tb-project\django-vue\myweb\20201103\20201103\ant-admin-exps\node_modules\esno\node_modules\esbuild-register\register.js "./build/script/preserve.ts"
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (G:\software\project\tb-project\django-vue\myweb\20201103\20201103\ant-admin-exps\node_modules\esno\esno.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16512,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vben-admin-2.0@2.0.0-rc.11 serve: `esno ./build/script/preserve.ts && cross-env NODE_ENV=development vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vben-admin-2.0@2.0.0-rc.11 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-12-06T12_19_04_221Z-debug.log

**Comment by anncwb** [comment]
删除node_modules和yarn.lock文件重新安装
