### ISSUE TITLE
The following dependencies are imported but could not be resolved

### ISSUE THREAD

**Issue by waney** [anncwb/vue-vben-admin#1427]
**更新 refactor(tree): Refactor tree to support antv3.0 之后报错：**

```
www@DESKTOP-RJ2Q4N0 MINGW64 ~/Downloads/vue-vben-admin-main
$ pnpm dev

> vben-admin@2.8.0 dev C:\Users\www\Downloads\vue-vben-admin-main
> vite

error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @vue/shared (imported by C:/Users/www/Downloads/vue-vben-admin-main/src/components/Tree/src/TreeIcon.ts)

Are they installed?
    at optimizeDeps (C:\Users\www\Downloads\vue-vben-admin-main\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:63718:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize (C:\Users\www\Downloads\vue-vben-admin-main\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:67723:48)
    at async Server.httpServer.listen (C:\Users\www\Downloads\vue-vben-admin-main\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:67739:21)
鈥塃LIFECYCLE鈥?Command failed with exit code 1.

```

**Comment by waney** [comment]
``
pnpm i @vue/shared
``

**Comment by xietongjian** [comment]
我也遇到了同样的问题。

**Comment by M69W** [comment]
https://github.com/anncwb/vue-vben-admin/commit/52257f061d95cf4a3b5a11e4a52c48774a6042be#diff-54c27e20fb06f48378dd26980137a2c69d7ead9290fa87e9238a2b993e428279R4
更新代码是不是这里？

**Comment by dearmark** [comment]
似乎在Ubuntu 18，我的vps上没有问题，像是 Windows 专属的错误。

**Comment by waney** [comment]
都不仔细看的吗？ pnpm i @vue/shared
