### ISSUE TITLE
pnpm serve报错， @vue/shared模块未找到

### ISSUE THREAD

**Issue by yuang01** [anncwb/vue-vben-admin#1429]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

克隆项目之后，pnpm install , 然后pnpm serve，之后，无法启动项目，报以下错误
``` bash
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @vue/shared (imported by D:/vue-vben-admin/src/components/Tree/src/TreeIcon.ts)

Are they installed?
    at optimizeDeps (D:\vue-vben-admin\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:63718:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOptimize (D:\vue-vben-admin\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:67723:48)
    at async Server.httpServer.listen (D:\vue-vben-admin\node_modules\.pnpm\vite@2.7.0-beta.9_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9aea22f6.js:67739:21)
```
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码
1. pnpm install 
2. pnpm serve

## 系统信息

- 操作系统: windows11 
- Node 版本: v12.18.3
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by pihc** [comment]
拉一下新代码，然后重新安装一下依赖就可以了

git pull origin main 

pnpm install

**Comment by yuang01** [comment]
好的好的
