### ISSUE TITLE
yarn serve 报错

### ISSUE THREAD

**Issue by xpsuper** [anncwb/vue-vben-admin#171]
failed to load config from /***/vue-vben-admin/vite.config.ts
error when starting dev server:
/***/vue-vben-admin/node_modules/vite-plugin-mock/dist/createMockServer.js:93
        next?.();
             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/blues/Program/Vue/vue-vben-admin/intact/node_modules/vite-plugin-mock/dist/index.js:17:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
error Command failed with exit code 1.

**Comment by anncwb** [comment]
Re-run yarn && yarn serve
