### ISSUE TITLE
win启动失败

### ISSUE THREAD

**Issue by superlbr** [anncwb/vue-vben-admin#180]
vite2版本，报错TypeError: defaultLoader is not a function
```
failed to load config from /Documents/vue-vben-admin/vite.config.ts
error when starting dev server:
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .ts] (D:\Documents\vue-vben-admin\node_modules\vite\dist\node\chunks\dep-30d01443.js:46937:13)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by anncwb** [comment]
close cdf0a60

**Comment by readpage** [comment]
?

**Comment by bytrix** [comment]
配置文件弄丢了吧？是不是拷贝项目的时候没把配置文件拷过来
