### ISSUE TITLE
Error: [Pirates] A hook returned a non-string, or nothing at all! This is a violation of intergalactic law!

### ISSUE THREAD

**Issue by jackchoumine** [anncwb/vue-vben-admin#184]
### Subject of the issue

Describe your issue here.

### Your environment

- **OS**: 
```bash
ProductName:	Mac OS X
ProductVersion: 10.15.7
BuildVersion:	19H15
```
- **Packages**:
```json
{
  "name": "vben-admin-2.0",
  "version": "2.0.0-rc.11",
  "scripts": {
    "bootstrap": "yarn install",
    "serve": "esno ./build/script/preserve.ts && cross-env NODE_ENV=development vite",
    "build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts",
    "build:site": "cross-env SITE=true npm run build ",
    "build:no-cache": "yarn  clean:cache && npm run build",
    "typecheck": "typecheck .",
    "report": "cross-env REPORT=true npm run build ",
    "preview": "npm run build && esno ./build/script/preview.ts",
    "preview:dist": "esno ./build/script/preview.ts",
    "log": "esno ./build/script/changelog.ts",
    "clean:cache": "rimraf node_modules/.cache/ && rimraf node_modules/.vite_opt_cache",
    "clean:lib": "npx rimraf node_modules",
    "ls-lint": "npx ls-lint",
    "lint:eslint": "eslint --fix --ext \"src/**/*.{vue,less,css,scss}\"",
    "lint:prettier": "prettier --write --loglevel warn \"src/**/*.{js,json,tsx,css,less,scss,vue,html,md}\"",
    "lint:stylelint": "stylelint --fix \"**/*.{vue,less,postcss,css,scss}\" --cache --cache-location node_modules/.cache/stylelint/",
    "reinstall": "rimraf yarn.lock && rimraf package.lock.json && rimraf node_modules && npm run bootstrap"
  },
  "dependencies": {
    "@iconify/iconify": "^2.0.0-rc.2",
    "@vueuse/core": "4.0.0-beta.41",
    "ant-design-vue": "2.0.0-beta.15",
    "axios": "^0.21.0",
    "js-audio-recorder": "^1.0.6",
    "lodash-es": "^4.17.15",
    "moment": "^2.29.1",
    "nprogress": "^0.2.0",
    "path-to-regexp": "^6.2.0",
    "vue": "^3.0.2",
    "vue-i18n": "^9.0.0-beta.7",
    "vue-router": "^4.0.0-rc.3",
    "vuex": "^4.0.0-rc.1",
    "vuex-module-decorators": "^1.0.1"
  },
  "devDependencies": {
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@iconify/json": "^1.1.260",
    "@ls-lint/ls-lint": "^1.9.2",
    "@purge-icons/generated": "^0.4.1",
    "@types/echarts": "^4.9.1",
    "@types/fs-extra": "^9.0.4",
    "@types/koa-static": "^4.0.1",
    "@types/lodash-es": "^4.17.3",
    "@types/nprogress": "^0.2.0",
    "@types/qrcode": "^1.3.5",
    "@types/rollup-plugin-visualizer": "^2.6.0",
    "@types/yargs": "^15.0.10",
    "@types/zxcvbn": "^4.4.0",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "@vue/compiler-sfc": "^3.0.2",
    "@vuedx/typecheck": "^0.2.4-0",
    "@vuedx/typescript-plugin-vue": "^0.2.4-0",
    "autoprefixer": "^9.8.6",
    "commitizen": "^4.2.2",
    "conventional-changelog-cli": "^2.1.1",
    "conventional-changelog-custom-config": "^0.3.1",
    "cross-env": "^7.0.2",
    "dotenv": "^8.2.0",
    "eslint": "^7.13.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-html": "^6.1.1",
    "eslint-plugin-javascript": "^1.3.4",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-vue": "^7.1.0",
    "esno": "^0.2.4",
    "fs-extra": "^9.0.1",
    "husky": "^4.3.0",
    "koa-static": "^5.0.0",
    "less": "^3.12.2",
    "lint-staged": "^10.5.1",
    "portfinder": "^1.0.28",
    "postcss-import": "^12.0.1",
    "prettier": "^2.1.2",
    "rimraf": "^3.0.2",
    "rollup-plugin-visualizer": "^4.1.2",
    "stylelint": "^13.8.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-order": "^4.1.0",
    "tasksfile": "^5.1.1",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.5",
    "vite": "^1.0.0-rc.9",
    "vite-plugin-html": "^1.0.0-beta.2",
    "vite-plugin-mock": "^1.0.6",
    "vite-plugin-purge-icons": "^0.4.5",
    "vite-plugin-pwa": "^0.1.5",
    "vue-eslint-parser": "^7.1.1",
    "yargs": "^16.1.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/anncwb/vue-vben-admin.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/anncwb/vue-vben-admin/issues"
  },
  "homepage": "https://github.com/anncwb/vue-vben-admin",
  "changelog": {
    "bugsUrl": "https://github.com/anncwb/vue-vben-admin/issues",
    "emojis": true,
    "authorName": false,
    "authorEmail": false
  },
  "husky": {
    "hooks": {
      "pre-commit": "ls-lint && lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "engines": {
    "node": ">=10.16.1"
  }
}
```
- **Env**: 
```bash
yarn 1.22.10
npm 6.14.5
node 12.18.1
```
### Steps to reproduce

安装了以上依赖后,运行报错:
```bash
$ esno ./build/script/preserve.ts && cross-env NODE_ENV=development vite
/Users/jack/work/aiclass-admin/node_modules/pirates/lib/index.js:1
Error: [Pirates] A hook returned a non-string, or nothing at all! This is a violation of intergalactic law!
--------------------
If you have no idea what this means or what Pirates is, let me explain: Pirates is a module that makes is easy to implement require hooks. One of the require hooks you're using uses it. One of these require hooks didn't return anything from it's handler, so we don't know what to do. You might want to debug this.
    at Object._compile (/Users/jack/work/aiclass-admin/node_modules/pirates/lib/index.js:96:21)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .ts] (/Users/jack/work/aiclass-admin/node_modules/pirates/lib/index.js:104:7)
child_process.js:669
    throw err;
    ^

Error: Command failed: node -r /Users/jack/work/aiclass-admin/node_modules/esm/esm.js -r /Users/jack/work/aiclass-admin/node_modules/esno/node_modules/esbuild-register/register.js "./build/script/preserve.ts"
```

**Comment by anncwb** [comment]
尝试升级到最新版。最新是rc.16

**Comment by jackchoumine** [comment]
> 尝试升级到最新版。最新是 rc.16

升级哪个依赖呢?
