### ISSUE TITLE
purge-icons_core

### ISSUE THREAD

**Issue by chaiyanliang** [anncwb/vue-vben-admin#226]
[vite] Internal server error: str.matchAll is not a function
      at Object.extractor (/Volumes/data/nodejs/vue-vben-admin/node_modules/_@purge-icons_core@0.6.0@@purge-icons/core/dist/index.js:154:27)
      at Extract (/Volumes/data/nodejs/vue-vben-admin/node_modules/_@purge-icons_core@0.6.0@@purge-icons/core/dist/index.js:181:54)

**Comment by anncwb** [comment]
node版本问题，升级到12以上。文档常见问题有
