### ISSUE TITLE
yarn serve 执行就报错

### ISSUE THREAD

**Issue by tomoat** [anncwb/vue-vben-admin#385]
◉  yarn serve
yarn run v1.22.10
$ npx --max_old_space_size=4096 vite
failed to load config from /Users/tomato/Sites/vue-test/vue-vben-admin/vite.config.ts
error when starting dev server:
Error: Cannot find module './build/vite/plugin/package.json'
Require stack:
- /Users/tomato/Sites/vue-test/vue-vben-admin/vite.config.ts
- /Users/tomato/Sites/vue-test/vue-vben-admin/node_modules/vite/dist/node/chunks/dep-5645e129.js
- /Users/tomato/Sites/vue-test/vue-vben-admin/node_modules/vite/dist/node/cli.js
- /Users/tomato/Sites/vue-test/vue-vben-admin/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tomato/Sites/vue-test/vue-vben-admin/vite.config.ts:15:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/tomato/Sites/vue-test/vue-vben-admin/node_modules/vite/dist/node/chunks/dep-5645e129.js:54855:20)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
npm ERR! code 1
npm ERR! path /Users/tomato/Sites/vue-test/vue-vben-admin
npm ERR! command failed
npm ERR! command sh -c vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomato/.npm/_logs/2021-03-17T20_23_38_726Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by anncwb** [comment]
尝试拉取最新代码重新安装依赖.这个是vite版本的问题

**Comment by tomoat** [comment]
git pull 了就是最新的代码啊， main分支

错误是这个路径找不到 Error: Cannot find module './build/vite/plugin/package.json'   github中build/vite/plugin这个路径下也没有package.json呢

**Comment by anncwb** [comment]
你可以查看node_modules内的vite的版本是不是2.0.5.最新代码你可以同现在的github对比下. 这个问题会在vite2.1.3发布后修复

**Comment by tomoat** [comment]
我删除node_modules,重新安装了一下，现在可以了，谢谢
