### ISSUE TITLE
yarn report 执行打包分析命令报错

### ISSUE THREAD

**Issue by Mr-Vash** [anncwb/vue-vben-admin#445]
### 项目:vben完整版
`D:\WWW\SysApp> yarn report
yarn run v1.22.10
$ cross-env REPORT=true npm run build

> vben-admin@2.1.1 build D:\WWW\SysApp
> vite build && esno ./build/script/postBuild.ts

vite v2.1.5 building for production...
transforming (4946) node_modules\cross-fetch\dist\browser-ponyfill.jsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 4947 modules transformed.
rendering chunks (290)...[visualizer] Error adding node to path 

✨ [vite-plugin-theme] - extract css code file is successfully:
dist/assets/app-theme-style.3wt0f9py.css

error during build:
Error: Error adding node to path 
    at addToPath (D:\WWW\SysApp\node_modules\rollup-plugin-visualizer\dist\plugin\data.js:12:15)
    at Object.buildTree (D:\WWW\SysApp\node_modules\rollup-plugin-visualizer\dist\plugin\data.js:46:13)
    at Object.generateBundle (D:\WWW\SysApp\node_modules\rollup-plugin-visualizer\dist\plugin\index.js:79:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Bundle.generate (D:\WWW\SysApp\node_modules\rollup\dist\shared\rollup.js:12445:9)
    at async handleGenerateWrite (D:\WWW\SysApp\node_modules\rollup\dist\shared\rollup.js:20272:23)
    at async doBuild (D:\WWW\SysApp\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44302:20)
    at async build (D:\WWW\SysApp\node_modules\vite\dist\node\chunks\dep-66eb515d.js:44174:16)
    at async CAC.<anonymous> (D:\WWW\SysApp\node_modules\vite\dist\node\cli.js:14072:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vben-admin@2.1.1 build: `vite build && esno ./build/script/postBuild.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vben-admin@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-04-04T07_08_23_789Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

### 修改了.env.production文件
`# public path
VITE_PUBLIC_PATH = ./`

### 尝试方法
删除dist文件，重新执行命令，还是报同样的错误

**Comment by anncwb** [comment]
安装下最新依赖 。 VITE_PUBLIC_PATH这个不能以 `.`开头，必须以`/`开头

**Comment by Mr-Vash** [comment]
rollup-plugin-visualizer 插件安装5.1.0+后，成功解决
