### ISSUE TITLE
Dependencies are imported but could not be resolved

### ISSUE THREAD

**Issue by mrs01dev** [anncwb/vue-vben-admin#476]
pnpm serve

> vben-admin@2.3.0 serve Q:\vben-admin
> cross-env --max_old_space_size=4096 vite

error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  moment (imported by Q:/vben-admin/src/utils/dateUtil.ts)
  @ant-design/colors (imported by Q:/vben-admin/build/config/themeConfig.ts)
  @ant-design/icons-vue (imported by Q:/vben-admin/src/components/Verify/src/DragVerify.tsx)
  resize-observer-polyfill (imported by Q:/vben-admin/src/utils/event/index.ts)
  qs (imported by Q:/vben-admin/src/utils/http/axios/Axios.ts)

Are they installed?
    at optimizeDeps (Q:\vben-admin\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:65570:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (Q:\vben-admin\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69322:48)
    at async Server.httpServer.listen (Q:\vben-admin\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69336:17)
 ERROR  Command failed with exit code 1.

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:windows
- Node version:v14.16.1
- Package manager (pnpm) and version:6.0.1

**Comment by anncwb** [comment]
Try to execute yarn reinstall
