### ISSUE TITLE
vue-tsc-0.0.23.tgz not found

### ISSUE THREAD

**Issue by guo-lei** [anncwb/vue-vben-admin#481]
作者，您好，首先感谢您提供这么好的前端快速开发框架。
在我初次使用，安装包的过程中，遇到了如下问题。
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\18170\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js

PATH: 
  C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Java\jdk1.8.0_211\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\nodejs\;C:\Users\18170\AppData\Local\Microsoft\WindowsApps;C:\tools\Cmder;;C:\Users\18170\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\18170\AppData\Roaming\npm

Yarn version: 
  1.22.10

Node version: 
  14.16.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.npmjs.org/vue-tsc/-/vue-tsc-0.0.23.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (C:\Users\18170\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:696:66)
      at new ResponseError (C:\Users\18170\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:802:124)
      at Request.<anonymous> (C:\Users\18170\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:67058:16)
      at Request.emit (events.js:315:20)
      at Request.module.exports.Request.onRequestResponse (C:\Users\18170\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141539:10)
      at ClientRequest.emit (events.js:315:20)
      at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:509:22)
      at TLSSocket.emit (events.js:315:20)

不知道是这个资源确实不存在了，还是别的问题。

我的操作系统是 windows10。
node版本：v14.16.1
yarn版本：1.22.10
npm版本：6.14.12

**Comment by Kchengz** [comment]
看了一下npm上面，vue-tsc-0.0.23被删除了，安装0.0.24版本就好了

**Comment by guo-lei** [comment]
> 看了一下npm上面，vue-tsc-0.0.23被删除了，安装0.0.24版本就好了

的确是，看到0.0.23被废弃了，现在好了，感谢！
