### ISSUE TITLE
yarn serve运行项目报错

### ISSUE THREAD

**Issue by zengxianguo** [anncwb/vue-vben-admin#558]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

failed to load config from G:\demo\vue-keycloak-js-master\vben-admin-thin-next\vite.config.ts
error when starting dev server:
Error: Build failed with 3 errors:
package.json:1:0: error: Unexpected "b"
package.json:1:0: error: Unexpected "b"
tsconfig.json:1:0: error: Unexpected "b"
    at failureErrorWithLog (G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:1224:15)
    at buildResponseToResult (G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:936:32)
    at G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:1035:20
    at G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:568:9
    at handleIncomingPacket (G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:657:9)
    at Socket.readFromStdout (G:\demo\vue-keycloak-js-master\vben-admin-thin-next\node_modules\vite\node_modules\esbuild\lib\main.js:535:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by xiaoxian521** [comment]
npm run bootstrap
npm run serve
