### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#841]
D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild-register\dist\node.js:2699
        throw error;
        ^

TypeError: MessagePort was found in message but not listed in transferList
    at new Worker (internal/worker.js:170:17)
    at startWorkerThreadService (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild\lib\main.js:1823:16)
    at transformSync (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild\lib\main.js:1652:29)
    at compile2 (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild-register\dist\node.js:2722:75)
    at Module._compile (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild-register\dist\node.js:2254:31)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at extensions..js (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild-register\dist\node.js:2696:24)
    at Object.newLoader [as .ts] (D:\BaiCai\BaiCai.Platform\src\BaiCai.Web\node_modules\esbuild-register\dist\node.js:2262:9)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST'
}

![image](https://user-images.githubusercontent.com/31719079/124093335-5917b500-da8a-11eb-8fef-c77e53f9f9dd.png)

**Comment by anncwb** [comment]
没别的信息，最好可以提供更多的内容或者你的改动。否则没法帮助你解决问题

**Comment by anncwb** [comment]
Hello @snihwxf. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by snihwxf** [comment]
我只是新添加了一个页面，其它的什么也没有改

**Comment by anncwb** [comment]
得提供下复现步骤，否则没法帮到你
