### ISSUE TITLE
运行报 str.matchAll is not a function

### ISSUE THREAD

**Issue by limuen** [anncwb/vue-vben-admin#97]
装好依赖直接yarn serve
然后就是下面的信息。

yarn run v1.22.10
$ esno ./build/script/preserve.ts && cross-env NODE_ENV=development vite
vite v1.0.0-rc.9
(node:64411) ExperimentalWarning: The fs.promises API is experimental

  Dev server running at:
  > Local:    http://localhost:3100/
  > Network:  http://192.168.31.247:3100/

  TypeError: str.matchAll is not a function
      at Object.extractor (/Users/limuen/Documents/vue/vue-vben-admin-main/node_modules/@purge-icons/core/dist/index.js:150:27)
      at Extract (/Users/limuen/Documents/vue/vue-vben-admin-main/node_modules/@purge-icons/core/dist/index.js:177:54)

**Comment by dahuoyzs** [comment]
why close？
